name: Publish Snapshot
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  snapshot:
    name: Deploy Snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up publishing to maven central
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: deploy
        run: |
          mvn --no-transfer-progress -DskipTests deploy
        env:
          MAVEN_USERNAME: ${{secrets.OSSRH_USER}}
          MAVEN_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
