name: Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Java with Maven cache
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
          server-id: oss
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Update version in Maven configuration
        run: |
          mvn --no-transfer-progress \
            --batch-mode \
            versions:set -DnewVersion=${{ github.event.release.tag_name  }}
        if: ${{ github.event.release.tag_name  }}

      - name: Install GPG key
        run: |
          cat <(echo -e "${{ secrets.GPG_SECRET }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish to Maven
        run: |
          mvn --no-transfer-progress \
            --batch-mode \
            -Dgpg.passphrase='${{ secrets.GPG_PASSWORD }}' \
            -DskipTests deploy -P sonatype-oss-release

        env:
          MAVEN_USERNAME: ${{secrets.OSSRH_USER}}
          MAVEN_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
